#!/usr/bin/env node
import { readFile } from "node:fs/promises";
import path from "node:path";
import { parseCli, publicError, REPO_ROOT, sha256, stableJson } from "./ops-lib.mjs";
import {
  expectedHostingBuild,
  HOSTING_APPS,
  validateFirebaseHostingConfig,
  validateHostingHtml,
} from "./hosting-lib.mjs";

async function main() {
  const args = parseCli(process.argv.slice(2), { help: "boolean" });
  if (args.help) {
    console.log("Usage: node scripts/leads/validate-hosting.mjs");
    return;
  }
  if (args._.length) throw new Error("Unexpected positional arguments");
  const expected = await expectedHostingBuild();
  const evidence = [];
  for (const [name, app] of Object.entries(HOSTING_APPS)) {
    const [source, output] = await Promise.all([readFile(app.source, "utf8"), readFile(app.output, "utf8")]);
    validateHostingHtml(name, output, { compareToSource: source });
    if (output !== expected.targets[name].html) throw new Error(`${name}: output bytes are stale`);
    evidence.push({ name, bytes: Buffer.byteLength(output), sha256: sha256(output) });
  }
  const manifestPath = path.join(REPO_ROOT, "firebase-leads/hosting/build-manifest.json");
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  if (stableJson(manifest) !== stableJson(expected.manifest)) throw new Error("build-manifest.json does not match generated bytes");
  const firebaseConfig = JSON.parse(await readFile(path.join(REPO_ROOT, "firebase-leads/firebase.json"), "utf8"));
  validateFirebaseHostingConfig(firebaseConfig);
  for (const item of evidence) console.log(`[PASS] ${item.name}: ${item.bytes} bytes sha256=${item.sha256}`);
  console.log("Hosting byte/content and anti-framing header invariants passed (2/2).");
}

main().catch((error) => {
  console.error(`ERROR: ${publicError(error)}`);
  process.exitCode = 1;
});
